/**
 * Canned state for the popup preview (`npm run preview`).
 *
 * One row per shape the renderer has to handle, because these are exactly the
 * ones a real account rarely shows all at once: a late window still open, a
 * reduced-credit ladder, an unbooked CBTF exam, a merged two-source row, an
 * 8 AM smartPhysics checkpoint, a course-site row whose time was invented, a
 * not-for-credit practice quiz, a deadline that moved, and a date the parser
 * could not read. If the layout survives this list it survives a real one.
 *
 * Not shipped: nothing imports it, and `dist/preview.*` is regenerated by the
 * script rather than by the build.
 */
import {
  type ManualInput,
  editManualItem,
  newManualItem,
} from "../src/core/manual.js";
import { SITE_TIMEZONE } from "../src/core/detect.js";
import { extractCourseCode } from "../src/core/normalize.js";
import type { RawItem } from "../src/sources/types.js";
import { referenceItems } from "./preview-reference.js";

const now = Date.now();
const at = (days: number, hour = 23, minute = 59) => {
  const d = new Date(now + days * 86_400_000);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};
let previewId = 0;
const member = (source: string, extra?: Record<string, string>, status = "not_submitted") => ({
  source, sourceId: `${source}-${++previewId}`, courseRaw: "x", title: "m",
  kind: "assignment", url: "https://www.gradescope.com/", status, extra,
  fetchedAt: new Date().toISOString(),
});
const item = (o: Record<string, unknown>) => ({
  id: `i${++previewId}`, members: [member("gradescope")], courseLabel: "CS357",
  title: "Thing", kind: "assignment", url: "https://www.gradescope.com/courses/1",
  status: "not_submitted", hidden: false, done: false, notified: {}, ...o,
});

const items = [
  // Real titles and shapes from Sushi's account, 2026-09-11. Invented titles
  // were consistently shorter than the ones UIUC courses actually use, which
  // is exactly the difference a layout fails on.
  item({ courseLabel: "CS357", title: "Book a slot: CS 357: Quiz 2", kind: "booking",
         members: [member("prairietest", { windowStart: at(10, 0, 1), windowEnd: at(12, 23, 59) })] }),
  // §4.4's room and duration, which the parser has recorded all along.
  // A December final: further out than the 60-day horizon every other view
  // stops at, which is the case the Exams tab exists for.
  item({ courseLabel: "CS357", title: "CS 357 Final Exam", dueAt: at(95, 8, 0), kind: "exam",
         members: [member("canvas", { location: "Foellinger Auditorium", duration: "180min" })] }),
  item({ courseLabel: "ECE374", title: "ECE 374 Midterm 2", dueAt: at(24, 19, 0), kind: "exam",
         members: [member("prairietest", { location: "Grainger Library",
                                           locationDetail: "Room 57", duration: "110min" })] }),
  item({ courseLabel: "CS357", title: "CS 357: Quiz 1", dueAt: at(0, 21, 0), kind: "exam",
         members: [member("prairietest", { location: "Grainger Library",
                                           locationDetail: "Room 57", duration: "50min" })] }),
  // ECE 374 guided problem sets, listed but not yet open. Real titles and real
  // opening times from the assessments page, 2026-09-11. Eight of these led the
  // list under "Couldn't read" before the parser knew the shape.
  item({ courseLabel: "ECE374", title: "GPS4 Language Transformations, and CFGs",
         members: [member("prairielearn", { releasedAt: at(1, 9, 0) })] }),
  item({ courseLabel: "ECE374", title: "GPS5 Divide and Conquer, Recursion, and Recurrences",
         members: [member("prairielearn", { releasedAt: at(15, 9, 0) })] }),
  // Handed in last week. Invisible until now: `hideSubmitted` filtered the
  // whole list regardless of date, so navigating back showed an empty week.
  item({ courseLabel: "CS357", title: "HW3 Errors and Big-O", dueAt: at(-3, 23, 59),
         status: "graded", members: [member("prairielearn", undefined, "graded")] }),
  item({ courseLabel: "CS425", title: "Reading response 3", dueAt: at(-4, 23, 59),
         status: "submitted", members: [member("gradescope", undefined, "submitted")] }),
  // Canvas calendar events, from the same real list. The recurring one is the
  // point: four instances of this block and two class Zoom links were sitting
  // in "Needs attention", where nothing could ever clear them.
  item({ courseLabel: "CS411", title: "Fall 2026 Office Hours", dueAt: at(0, 20, 0),
         kind: "event", members: [member("canvas")] }),
  item({ courseLabel: "CS411", title: "Class Zoom (only for students with excused absence)",
         dueAt: at(1, 14, 0), kind: "event", members: [member("canvas")] }),
  item({ courseLabel: "CS425", title: "MP1 Report (4cr only, EXCEPT for students in MC3)",
         dueAt: at(3, 23, 59), members: [member("gradescope")] }),
  item({ courseLabel: "CS357", title: "L5 Rounding and Cancellation", dueAt: at(4, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "L6 Taylor Series", dueAt: at(4, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "HW5 Rounding and Cancellation", dueAt: at(4, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "PHYS435", title: "Homework 3", dueAt: at(5, 17),
         members: [member("gradescope")] }),
  item({ courseLabel: "CS424", title: "Homework 1", dueAt: at(5, 23, 59),
         members: [member("canvas"), member("site")] }),
  item({ courseLabel: "CS357", title: "HW6 Taylor Series", dueAt: at(6, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS425", title: "HW1", dueAt: at(9, 23, 59),
         members: [member("gradescope")] }),
  // Listed by a source with no date on it anywhere. Three of them, so the
  // folded group has something to fold — it is the shape that made Attention
  // read "11" when one thing was actually late.
  item({ courseLabel: "CS357", title: "Research study survey (extra credit)",
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "Select your group (NOT FOR CREDIT)",
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS411", title: "Course syllabus acknowledgement",
         members: [member("canvas")] }),
  // Today at 11:59 PM — the commonest deadline there is, and the one the
  // harness was missing. An item on the last minute of the grid is drawn one
  // pixel before the bottom edge, and its wrapped lines landed on top of the
  // status line underneath. The fixture day had nothing at 11:59 PM, so the
  // preview could not reproduce it and Sushi found it on real data instead.
  item({ courseLabel: "CS425", title: "MP1 Report (4cr only, EXCEPT Coursera)",
         dueAt: at(0, 23, 59), members: [member("gradescope")] }),
  // Today, so the untimed band has something in it: the band is the row shape
  // that is hardest to see in the extension and easiest to get wrong.
  item({ courseLabel: "CS424", title: "Homework 1", dueAt: at(0, 23, 59), timeAssumed: true,
         members: [member("site", { timeAssumed: "true" })] }),
  item({ courseLabel: "CS424", title: "HW2 Due", dueAt: at(12, 23, 59), timeAssumed: true,
         members: [member("site", { timeAssumed: "true" })] }),
  // Handed in, with a late window still open. From Sushi's real Gradescope:
  // PHYS 435 Homework 2, submitted, due Sep 9, "accepting late submissions"
  // until Sep 16. It appeared nowhere at all — `liveDeadline` anchored it to
  // the late date, so it was hidden as finished-but-not-yet-past and never
  // drawn on the day it was actually due.
  item({ courseLabel: "PHYS435", title: "Homework 2 (submitted, late window open)",
         dueAt: at(-3, 17, 0), lateDueAt: at(4, 17, 0), status: "submitted",
         members: [member("gradescope", undefined, "submitted")] }),
  // The same shape from PrairieLearn: scored, with a reduced-credit tail. By
  // October this is most of a semester's work.
  item({ courseLabel: "CS357", title: "L4a Floating Point (scored, 80% tail)",
         dueAt: at(-3, 23, 59), lateDueAt: at(10, 23, 59), status: "graded",
         members: [member("prairielearn", { creditRemaining: "80" }, "graded")] }),
  // Shapes his account does not currently have, kept so the layout is still
  // exercised against them: a still-open late window, a reduced-credit ladder,
  // an 8 AM smartPhysics checkpoint, a practice quiz, a moved deadline, and a
  // date the parser could not read.
  item({ courseLabel: "PHYS435", title: "Homework 2", dueAt: at(-1, 17, 0),
         lateDueAt: at(6, 17, 0), members: [member("gradescope")] }),
  item({ courseLabel: "CS357", title: "L4a Floating Point", dueAt: at(-2, 11),
         lateDueAt: at(12, 23), members: [member("prairielearn", { creditRemaining: "80" })] }),
  item({ courseLabel: "PHYS214", title: "Harmonic waves — Checkpoint", dueAt: at(0, 8, 0),
         kind: "quiz", members: [member("smartphysics", { creditRemaining: "100" })] }),
  item({ courseLabel: "CS357", title: "PQ1 Practice Quiz 1 (NOT FOR CREDIT)", dueAt: at(1, 23),
         forCredit: false, members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "HW4a Errors and Big-O", dueAt: at(2, 23),
         movedFrom: at(1, 23), members: [member("prairielearn")] }),
  item({ courseLabel: "CS425", title: "Reading response 4",
         members: [member("gradescope", { unparsedDueDate: "2026-09-31 17:00:00 -0500" })] }),
  /*
   * A row the student typed in (§3's `manual` source), so the ME chip, the
   * course colour and the Edit / Delete entries in the row menu are all
   * reachable here. Wave 1 shipped the source with no UI, so nothing in the
   * harness had ever drawn one.
   */
  // The typed row is seeded below, from `manualRaw`, so that its id is the one
  // Edit and Delete address. A hand-written `item({...})` here would draw
  // correctly and then be undeletable, which is a harness that lies.
  /*
   * Finished, and still ahead of its deadline — the case the beta report was
   * about ("completed assignments from prairielearn don't show up in the
   * calendar"). It has to be *future* and *graded* at once: a past finished row
   * was already drawable, and the one that vanished was the one handed in early.
   * Wave 1 fixed the behaviour and could not show it, because no canned row had
   * this shape.
   */
  item({ courseLabel: "CS357", title: "HW7 Interpolation (handed in early)",
         dueAt: at(3, 23, 59), status: "graded",
         members: [member("prairielearn", undefined, "graded")] }),
];

/**
 * The typed rows, as the worker keeps them: in `manualItems`, never in `raw`.
 *
 * The preview has no store, so the list the page reads is rebuilt from these
 * the way `dedupeInput` splices them in — enough for the harness to show a row
 * appearing at the time it was given, which is the thing being checked.
 */
let manualRaw: RawItem[] = [];

function itemOfManual(raw: RawItem): Record<string, unknown> {
  const code = raw.courseCode ?? extractCourseCode(raw.courseRaw) ?? raw.courseRaw;
  return {
    id: `manual-${raw.sourceId}`,
    members: [raw],
    courseLabel: code,
    title: raw.title,
    kind: raw.kind,
    ...(raw.dueAt ? { dueAt: raw.dueAt } : {}),
    ...(raw.url ? { url: raw.url } : {}),
    ...(raw.extra?.["timeAssumed"] === "true" ? { timeAssumed: true } : {}),
    status: raw.status,
    hidden: false,
    done: false,
    notified: {},
  };
}

/*
 * A row the student typed in (§3's `manual` source), so the ME chip, the course
 * colour and the Edit / Delete entries in the row menu are all reachable here.
 * Wave 1 shipped the source with no UI, so nothing in the harness had ever
 * drawn one.
 *
 * Built by the real `newManualItem` and spliced in the way `dedupeInput` does,
 * rather than written out as a finished `Item`: the id, the `endAt` and the
 * `timeAssumed` mark then agree with what the worker would have stored.
 */
const seeded = newManualItem(
  {
    title: "Group project check-in",
    courseRaw: "CS 411",
    // `en-CA` is `YYYY-MM-DD`, which is what §3 wants and what the editor's
    // `<input type="date">` produces.
    date: new Date(now + 2 * 86_400_000).toLocaleDateString("en-CA"),
    time: "16:00",
    endTime: "17:30",
    kind: "event",
  },
  new Date().toISOString(),
  SITE_TIMEZONE,
);
manualRaw.push(seeded);
items.push(itemOfManual(seeded) as (typeof items)[number]);

let setupDone = false;

const query = new URLSearchParams(location.search);
const dataset = query.get("dataset");
if (dataset && !["reference", "stress", "empty"].includes(dataset)) {
  throw new Error(`Unknown preview dataset: ${dataset}`);
}
if (dataset === "reference" || dataset === "empty") {
  manualRaw = [];
  items.splice(0, items.length, ...(dataset === "reference" ? referenceItems(now) : []) as (typeof items));
}
if (dataset === "stress") {
  items.push(item({ courseLabel: "ECE374", title: "A deliberately long deadline title: language transformations, recursive algorithms, and the full instructions students need to distinguish this assignment from its neighbours", dueAt: at(0, 15, 0) }));
}

/**
 * `?stale=1` — a worker on an older build than the page.
 *
 * The one state on the options page that is hard to reach and expensive to get
 * wrong: an older worker does not send every field the page dereferences, and
 * the page used to throw halfway through drawing with nothing on screen to say
 * that one click on chrome://extensions was the fix (worker rule 8).
 */
const stale = query.has("stale");
/**
 * `?piazza=read` — Piazza after a sync that actually read something.
 *
 * The default below is `needs_login`, because that is the only observer state
 * with a control beside it. It is also the one state whose row says nothing
 * about *what was read*, so the sentence the row was rewritten for — "25 posts,
 * 1 deadline found" — is unreachable in the harness without this.
 */
const piazzaRead = query.has("piazza");

/**
 * `?gcal=<state>` — the Google Calendar section in each of its states.
 *
 * Eight of the nine states cannot be reached without a Google account, a
 * Workspace policy or a revoked grant, and `admin_blocked` in particular is one
 * nobody outside an @illinois.edu tenant can produce at all. A harness that can
 * only draw the happy path is a harness that has never seen the sentences a
 * student in trouble reads.
 *
 * `?gcal=connected` is deliberately the *pushed* shape — the one with a number
 * on it — because that is the only state allowed to be green, and looking at
 * it beside `?gcal=fresh` (connected, nothing pushed) is the whole of worker
 * rule 2 in two screenshots.
 */
const gcalState = query.get("gcal");

function previewGcal(): Record<string, unknown> {
  const base = { enabled: true, byItemId: {}, calendarId: "illini-dash-preview" };
  switch (gcalState) {
    case null:
    case "off":
      return { enabled: false, byItemId: {}, state: "never" };
    case "fresh":
      return { ...base, state: "connected" };
    case "connected":
      return {
        ...base,
        state: "connected",
        lastPushAt: new Date(now - 4 * 60_000).toISOString(),
        lastPushCount: 14,
      };
    case "empty":
      return {
        ...base,
        state: "connected",
        lastPushAt: new Date(now - 60_000).toISOString(),
        lastPushCount: 0,
      };
    default:
      // Any other value is passed straight through, so a state added later is
      // reachable in the harness without editing this file.
      return { ...base, state: gcalState };
  }
}

/** The build the page was compiled with, injected by scripts/preview.mjs. */
const pageBuild =
  (globalThis as unknown as { __PREVIEW_BUILD__?: string }).__PREVIEW_BUILD__ ?? "dev";

// Source *keys*, the way the worker actually sends them — the page is what
// turns them into names, and a stub that pre-names them cannot catch it failing
// to.
const courses = [
  { key: "cs357", label: "CS357", itemCount: 12, sources: ["prairielearn", "canvas"], disabled: false },
  { key: "cs425", label: "CS425", itemCount: 5, sources: ["gradescope"], disabled: false },
  { key: "cs424", label: "CS424", itemCount: 3, sources: ["site"], disabled: false },
  { key: "ece374", label: "ECE374", itemCount: 7, sources: ["prairietest", "prairielearn"], disabled: false },
  { key: "phys435", label: "PHYS435", itemCount: 4, sources: ["gradescope"], disabled: true },
  { key: "phys214", label: "PHYS214", itemCount: 6, sources: ["smartphysics"], disabled: false },
  { key: "cs411", label: "CS411", itemCount: 2, sources: ["canvas"], disabled: false },
];

const setAsideCourses = [
  { id: "48211", name: "Academic Integrity Training", courseCode: "AIT",
    reason: "Canvas lists no term for it" },
];

const adapters: Record<string, unknown>[] = [
  { id: "cs424-fa26", label: "CS 424 course site", courseCode: "CS424",
    url: "https://courses.grainger.illinois.edu/cs424/fa2026/schedule/",
    hostPattern: "https://courses.grainger.illinois.edu/*",
    enabled: true, granted: true, currentTerm: true },
  { id: "phys214-fa26", label: "PHYS 214 course site", courseCode: "PHYS214",
    url: "https://physics.illinois.edu/phys214/schedule",
    hostPattern: "https://physics.illinois.edu/*",
    enabled: true, granted: false, currentTerm: true },
  // Two pages of one course: the shape that made a flat list unreadable, since
  // both rows were called "ECE 411 course site" on the same host. The second is
  // switched on without permission, so one group carries both a healthy row and
  // a "Permission missing" one.
  { id: "ece411-fa26-assignments", label: "ECE 411 assignments", courseCode: "ECE411",
    url: "https://courses.grainger.illinois.edu/ece411/fa2026/assignments.html",
    hostPattern: "https://courses.grainger.illinois.edu/*",
    enabled: true, granted: true, currentTerm: true },
  { id: "ece411-fa26-exams", label: "ECE 411 exams", courseCode: "ECE411",
    url: "https://courses.grainger.illinois.edu/ece411/fa2026/exams.html",
    hostPattern: "https://courses.grainger.illinois.edu/*",
    enabled: true, granted: false, currentTerm: true },
  // One the student added themselves, which is the only kind with a Remove
  // button. `local` is set by the worker and is not on the response type, so
  // without an entry carrying it here the button was unreachable in the harness.
  { id: "cs233-fa2026-local", label: "CS 233 course site", courseCode: "CS233",
    term: "fa2026",
    url: "https://courses.grainger.illinois.edu/cs233/fa2026/schedule.html",
    hostPattern: "https://courses.grainger.illinois.edu/*",
    rows: "table tr", title: "td:nth-child(1)", due: "td:nth-child(2)",
    dateFormat: "M/D/YYYY", timezone: "America/Chicago", minExtensionVersion: "1.0.0",
    enabled: true, granted: true, local: true, currentTerm: true },
];

const sessionFlags: Record<string, unknown> = {};
const listeners: ((changes: unknown, area: string) => void)[] = [];
function fireSession(values: Record<string, unknown>): void {
  const changes = Object.fromEntries(Object.entries(values).map(([k, v]) => [k, { newValue: v }]));
  for (const fn of listeners) fn(changes, "session");
}

declare const __MANIFEST_VERSION__: string;

const sources = {
  // `?fail=` picks a failure to look at: `network` is the one Sushi hit on a
  // live run (Gradescope, fixed by pressing Sync now), `parse` is a page that
  // really did change shape. Neither state was reachable in the harness before,
  // which is why the pill could describe both with one sentence for a week.
  canvas: query.get("fail") === "parse"
    ? { source: "canvas", enabled: true, state: "parse_error", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date(now - 3 * 3600_000).toISOString(), lastError: "canvas: 0 items where it previously had some", consecutiveFailures: 1 }
    : { source: "canvas", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  // `fail=parse` clears this one deliberately: a login outranks a parse error
  // in the pill, so leaving Gradescope signed out means the `parse` shot shows
  // the login sentence and never captures the state it is named for.
  gradescope: query.get("fail") === "network"
    ? { source: "gradescope", enabled: true, state: "network_error", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date(now - 35 * 60_000).toISOString(), lastError: "TypeError: Failed to fetch", consecutiveFailures: 1 }
    : query.get("fail") === "parse"
      ? { source: "gradescope", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 }
      // `lastAttemptAt` two minutes back rather than `now`: a source that just
      // this second failed a login is the one shape the return-from-signing-in
      // path cannot occur in, because `sourcesToRecheck` debounces it. Dating
      // it `now` made the harness the only place that bug could not be seen.
      : { source: "gradescope", enabled: true, state: "needs_login", lastAttemptAt: new Date(now - 2 * 60_000).toISOString(), lastSuccessAt: new Date(now - 40 * 3600_000).toISOString(), lastError: "401 at https://www.gradescope.com/login", consecutiveFailures: 2 },
  prairielearn: { source: "prairielearn", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  prairietest: { source: "prairietest", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  smartphysics: { source: "smartphysics", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  // `?fail=sitelogin`: the course-website source signed out. Its own state, not
  // a variant of another source's, because it is the only source with no fixed
  // login form — which is exactly how it came to render "Sign in needed" with
  // nothing beside it. Unreachable here until now, so nothing could see it.
  site: query.get("fail") === "sitelogin"
    ? { source: "site", enabled: true, state: "needs_login", lastAttemptAt: new Date(now - 2 * 60_000).toISOString(), lastSuccessAt: new Date(now - 26 * 3600_000).toISOString(), lastError: "401 at https://courses.grainger.illinois.edu/cs424/fa2026/secure/schedule.html", loginUrl: "https://courses.grainger.illinois.edu/cs424/fa2026/secure/schedule.html", consecutiveFailures: 2 }
    : { source: "site", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
};

// Reference and empty views start healthy; explicit failure switches still win.
if ((dataset === "reference" || dataset === "empty") && !query.has("fail")) {
  Object.assign(sources.gradescope, { state: "ok", consecutiveFailures: 0,
    lastAttemptAt: new Date(now).toISOString(), lastSuccessAt: new Date(now).toISOString(), lastError: undefined });
}

(globalThis as unknown as { chrome: unknown }).chrome = {
  runtime: {
    sendMessage: async (req: { type: string }) => {
      /*
       * A real sync is five or six fetches and takes five to ten seconds.
       *
       * The stub answered instantly, so every state that only exists *during* a
       * request was unreachable in the harness — which is why the header spent a
       * week asserting the previous sync's outcome while the next one ran, with
       * nobody able to see it. `?slow=` sets the delay; the default is enough to
       * notice and short enough not to make the preview annoying.
       */
      if (req.type === "set-course-name") {
        return { type: "ok" };
      }
      /*
       * The `manual` source, against the real `core/manual.ts`.
       *
       * Imported rather than re-implemented: the sentences a refusal shows are
       * the whole UI for an error, and a stub that invented its own would make
       * the one state worth looking at — a date the student typed wrong — the
       * one state the harness cannot show truthfully.
       */
      if (req.type === "add-manual-item" || req.type === "edit-manual-item") {
        const { input, sourceId } = req as { input: ManualInput; sourceId?: string };
        const existing = sourceId
          ? manualRaw.find((raw) => raw.sourceId === sourceId)
          : undefined;
        let raw: RawItem;
        try {
          raw = existing
            ? editManualItem(existing, input, new Date().toISOString(), SITE_TIMEZONE)
            : newManualItem(input, new Date().toISOString(), SITE_TIMEZONE);
        } catch (err) {
          return { type: "error", message: err instanceof Error ? err.message : String(err) };
        }
        if (existing) {
          manualRaw = manualRaw.map((one) => (one.sourceId === raw.sourceId ? raw : one));
          const at_ = items.findIndex((one) => one.id === `manual-${raw.sourceId}`);
          if (at_ >= 0) items[at_] = itemOfManual(raw);
        } else {
          manualRaw = [...manualRaw, raw];
          items.push(itemOfManual(raw));
        }
        return { type: "ok" };
      }
      if (req.type === "delete-manual-item") {
        const { sourceId } = req as { sourceId: string };
        manualRaw = manualRaw.filter((one) => one.sourceId !== sourceId);
        const at_ = items.findIndex((one) => one.id === `manual-${sourceId}`);
        if (at_ >= 0) items.splice(at_, 1);
        return { type: "ok" };
      }
      if (req.type === "sync") {
        // Counted so a test can ask whether returning to the page actually
        // fetched, rather than only whether it redrew — which is the whole of
        // the 2026-09-12 defect.
        const seen = globalThis as unknown as { __syncs?: string[] };
        seen.__syncs = [...(seen.__syncs ?? []), (req as { trigger?: string }).trigger ?? "?"];
        const ms = Number(query.get("slow") ?? 1200);
        // Published and cleared around the wait, like the worker does, so the
        // "a sync is running" state is reachable here at all.
        sessionFlags["illini-dash.syncing"] = true;
        fireSession({ "illini-dash.syncing": true });
        if (Number.isFinite(ms) && ms > 0) await new Promise((r) => setTimeout(r, ms));
        sessionFlags["illini-dash.syncing"] = false;
        fireSession({ "illini-dash.syncing": false });
      }
      // `?setup=1` shows the first-run screen, which is otherwise reachable
      // only by installing the extension into a clean Chrome profile — the
      // single hardest state in this project to look at.
      if (req.type === "complete-setup") {
        setupDone = true;
        return { type: "ok" };
      }
      if (req.type === "get-setup") {
        if (setupDone || !new URLSearchParams(location.search).has("setup")) {
          return { type: "setup" };
        }
        return {
          type: "setup",
          rows: [
            { source: "canvas", label: "Canvas", hint: "Every UIUC course",
              enabled: true, status: { ...sources.canvas, state: "ok" } },
            { source: "gradescope", label: "Gradescope", hint: "Most CS, ECE and Math courses",
              enabled: true, status: { source: "gradescope", enabled: true, state: "needs_login", consecutiveFailures: 1 } },
            { source: "prairielearn", label: "PrairieLearn", hint: "CS and ECE homework and quizzes",
              enabled: true, status: { source: "prairielearn", enabled: true, state: "pending", consecutiveFailures: 0 } },
            { source: "prairietest", label: "PrairieTest", hint: "Exams booked at the CBTF",
              enabled: false, status: { source: "prairietest", enabled: false, state: "disabled", consecutiveFailures: 0 } },
            { source: "smartphysics", label: "smartPhysics", hint: "PHYS 211, 212, 213 and 214 only",
              enabled: false, status: { source: "smartphysics", enabled: false, state: "disabled", consecutiveFailures: 0 } },
          ],
        };
      }
      if (req.type === "open-full-view") {
        // The worker focuses an existing tab in the extension; in the harness
        // there is no tab to focus, so this just says so rather than silently
        // doing nothing and looking like the bug it fixes.
        console.log("[preview] open-full-view — the worker would focus or open the tab");
        return { type: "ok" };
      }
      if (req.type === "ping") {
        // A different id is what the page compares against to decide whether
        // the worker is stale, so `?stale=1` has to change this too.
        return { type: "pong", buildId: stale ? "20260101T000000" : pageBuild };
      }
      if (req.type === "get-options-state") {
        const base = {
          type: "options-state",
          sources,
          settings: { leadTimes: ["24h", "2h"], quietHours: { start: 23, end: 8 },
                      hideSubmitted: true, remindNotForCredit: false, pollMinutes: 30 },
          courses,
          hiddenItems: [{ id: "h1", courseLabel: "CS411", title: "Course syllabus acknowledgement" }],
          doneItems: [{ id: "d1", courseLabel: "CS424", title: "Homework 1" }],
          setAsideCourses,
          // One course renamed and one not, so both halves of the control are
          // visible at once: a filled box beside an empty one whose placeholder
          // is the derived label.
          courseNames: { CS424: "Real-Time Systems" },
          // Switched on and having actually read something, because the state
          // worth looking at in the preview is the one the row derives rather
          // than the one the switch asserts.
          observers: {
            campuswire: {
              enabled: true,
              lastObservedAt: new Date().toISOString(),
              postsSeen: 3,
            },
            // Piazza in the state that has a button: `needs_login` is the only
            // observer state with a control beside it, so it is the one the
            // harness has to be able to show.
            piazza: piazzaRead
              ? {
                  enabled: true,
                  state: "ok",
                  lastAttemptAt: new Date().toISOString(),
                  lastObservedAt: new Date().toISOString(),
                  postsSeen: 25,
                  deadlinesFound: 1,
                }
              : {
                  enabled: true,
                  state: "needs_login",
                  lastAttemptAt: new Date().toISOString(),
                },
          },
          gcal: previewGcal(),
          notificationsBlocked: false,
        };
        // An older worker does not have the field at all — this is the exact
        // shape that threw, so the preview reproduces the omission rather than
        // sending an empty array.
        if (stale) delete (base as Record<string, unknown>)["setAsideCourses"];
        // A worker from before Google Calendar landed sends no `gcal` at all,
        // which is the case `core/compat.ts` fills in as "Off".
        if (stale) delete (base as Record<string, unknown>)["gcal"];
        return base;
      }
      // Remove and Undo against the stub. Without these the harness answered
      // `ok` and changed nothing, so the list redrew identically and "Removed ·
      // Undo" appeared over a row that was still there — a harness that cannot
      // show the bug it is there to show.
      if (req.type === "remove-local-adapter") {
        const at = adapters.findIndex((a) => a["id"] === req.adapterId);
        if (at >= 0) adapters.splice(at, 1);
        return { type: "ok" };
      }
      if (req.type === "add-local-adapter") {
        const adapter = req.adapter as Record<string, unknown>;
        adapters.push({ ...adapter, enabled: false, granted: true, local: true, currentTerm: true });
        return { type: "ok" };
      }
      if (req.type === "set-adapter-enabled") {
        const found = adapters.find((a) => a["id"] === req.adapterId);
        if (found) found["enabled"] = req.enabled;
        return { type: "ok" };
      }
      if (req.type === "get-adapters") {
        return {
          type: "adapters",
          adapters,
          fetchedAt: new Date(now - 5 * 60_000).toISOString(),
        };
      }
      if (
        req.type === "gcal-connect" ||
        req.type === "gcal-disconnect" ||
        req.type === "gcal-push-now"
      ) {
        // The harness has no Google account, so these answer the way the worker
        // does on the happy path and the section redraws from `?gcal=`. Say so
        // in the console rather than silently returning ok, which is what made
        // the adapter Remove button look like it worked when it did not.
        console.log(`[preview] ${req.type} — the worker would talk to Google here`);
        return { type: "ok" };
      }
      if (req.type === "get-diagnostics") {
        return { type: "diagnostics", report: "illini-dash diagnostics (preview)" };
      }
      if (req.type === "export") {
        return { type: "export", json: "{}" };
      }
      if (req.type === "get-state") {
        // `courseNames` has been part of this message since the rename tool
        // landed, and the stub never sent it — so every page this harness drew
        // carried the stale-worker warning at the foot of the document, about
        // a field the real worker does send. A harness that cries wolf on the
        // happy path is one nobody reads on the unhappy one; `?stale=1` is
        // where that state belongs.
        return { type: "state",
          observers: { piazza: { enabled: false, state: "pending" }, campuswire: { enabled: false } }, items, sources, notificationsBlocked: false,
                 suggestions: PREVIEW_SUGGESTIONS,
                 courseNames: stale ? undefined : { CS424: "Real-Time Systems" },
                 settings: { leadTimes: ["24h", "2h"], quietHours: { start: 23, end: 8 },
                             hideSubmitted: true, remindNotForCredit: false, pollMinutes: 30 },
                 lastSyncAt: new Date().toISOString() };
      }
      return { type: "ok" };
    },
    getURL: (p: string) => p,
    // `__MANIFEST_VERSION__` is defined from public/manifest.json by
    // preview.mjs. It was "0.1.0" here while the manifest said 1.0.0, so every
    // Settings capture stated a version that does not exist — on images that
    // are candidates for the store listing.
    getManifest: () => ({ version: __MANIFEST_VERSION__, name: "Illini Dash" }),
    openOptionsPage: () => undefined,
  },
  tabs: { create: () => undefined },
  // The options page asks before fetching any host outside the four sources.
  // Answering "granted" keeps the preview on the path a real profile takes
  // after the first prompt.
  permissions: {
    contains: async () => true,
    request: async () => true,
  },
  // Present because the real page has it, not because the preview needs it.
  // The live-refresh listener threw here and the harness said nothing — the
  // same shape as every other bug this preview has missed: a state it could
  // not reach. `fireStorageChange()` on the console drives a redraw.
  storage: {
    local: { get: async () => ({}), set: async () => undefined },
    // `session` is where the worker publishes whether a sync is in flight, so
    // that a page can say "Checking…" about work it did not start. Stubbed with
    // a real store rather than an empty one, because the state that matters
    // here is the flag being *true* while the page draws — and a stub that
    // always answers `{}` is a harness in which that can never happen.
    session: {
      get: async (key: string) => ({ [key]: sessionFlags[key] }),
      set: async (values: Record<string, unknown>) => {
        Object.assign(sessionFlags, values);
        fireSession(values);
      },
    },
    onChanged: {
      addListener: (fn: (changes: unknown, area: string) => void) => {
        listeners.push(fn);
        (globalThis as unknown as { fireStorageChange: () => void }).fireStorageChange = () =>
          fn({ illiniDue: { newValue: {} } }, "local");
      },
    },
  },
};

/* -------------------------------------------------------------------------- */
/* Deadlines read out of a post (§4.6)                                         */
/* -------------------------------------------------------------------------- */

/**
 * Appended at the end of the file on purpose: two workers were editing the rows
 * above, and this needs none of them.
 *
 * One suggestion whose clock the post stated and one whose 23:59 is this code's
 * invention, because the row draws them differently and the difference is the
 * whole of worker rule 3 at the surface.
 */
const PREVIEW_SUGGESTIONS = [
  {
    id: "s1", kind: "new", title: "MP3", courseRaw: "CS 425", courseCode: "CS425",
    at: at(15, 23, 59), timeAssumed: false,
    span: "Fri Oct 3 at 11:59pm", context: "MP3 is due Fri Oct 3 at 11:59pm.",
    source: "campuswire", postId: "campuswire:G794D32E4:682", postedAt: at(-1, 15, 0), createdAt: at(-1, 15, 1),
  },
  {
    id: "s2", kind: "new", title: "Quiz 1", courseRaw: "CS 357", courseCode: "CS357",
    at: at(9, 23, 59), timeAssumed: true,
    span: "10/12", context: "Quiz 1 is due 10/12. It opens on PrairieLearn the morning of.",
    source: "piazza", postId: "piazza:k5p6s9m2d1x:412", postedAt: at(-2, 9, 0), createdAt: at(-2, 9, 1),
    // Only one of the two carries `postSubject`, because that is the pair the
    // row has to draw: a suggestion written by this build names its post, and
    // one written before the field existed keeps the old wording (worker rule
    // 8). `s1` above deliberately has none.
    postSubject: "Quiz 1 logistics and the PrairieLearn window",
  },
  /*
   * The two the "from the …" line is now decided by, appended for the same
   * reason as the block itself.
   *
   * `s3` is Sushi's live row of 2026-09-19: a subject-derived title, cut at its
   * first parenthesis, with the whole ninety-character subject still on the
   * grey line — the pair that has to be legible on one clipped line at 400px.
   * `s4` is the other half of the rule: the title *is* the whole subject, so
   * quoting it underneath would draw the same words twice and the row falls
   * back to "from a Piazza post".
   */
  {
    id: "s3", kind: "new", title: "MP1 Demo Signups May have moved location",
    courseRaw: "CS 425 / ECE 428", courseCode: "CS425",
    at: at(1, 23, 59), timeAssumed: true,
    span: "9/20", context: "Please sign up for a demo slot by 9/20.",
    source: "piazza", postId: "piazza:k5p6s9m2d1x:145", postedAt: at(-1, 9, 0), createdAt: at(-1, 9, 1),
    postSubject:
      "MP1 Demo Signups May have moved location (+ Reminder to TAG your MP1 report on Gradescope)",
  },
  {
    id: "s4", kind: "new", title: "MP2", courseRaw: "CS 425 / ECE 428", courseCode: "CS425",
    at: at(8, 23, 59), timeAssumed: true,
    span: "9/27", context: "MP2 is due 9/27.",
    // Left in the pre-2026-09-19 shape on purpose: `postUrl` can address every
    // other row here, and this one has to keep the plain "from a Piazza post"
    // sentence so the harness shows both branches. An id this shape is what a
    // suggestion written by an older build carries (worker rule 8).
    source: "piazza", postId: "pz-160", postedAt: at(-1, 10, 0), createdAt: at(-1, 10, 1),
    postSubject: "MP2",
  },
];

// One row a post moved, so the detail line and its undo are on screen.
if (dataset !== "reference" && dataset !== "empty") items.push(
  item({
    courseLabel: "CS425", title: "MP2: Distributed Logging", dueAt: at(5, 23, 59),
    movedBy: { reason: "Campuswire post 2026-09-17", from: at(2, 23, 59), postId: "campuswire:G794D32E4:640" },
  }),
);

/* -------------------------------------------------------------------------- */
/* "Add a course site", and the on-device model behind it                       */
/* -------------------------------------------------------------------------- */

/**
 * Appended at the end, like the block above, because it needs none of the rows
 * above it and two workers are editing them.
 *
 * `?model=ok|fail|absent` drives the three status lines the add-site flow can
 * end on. They cannot be reached any other way in a harness: the real Prompt
 * API needs 22GB of free disk and a 4GB GPU, so on most machines — including
 * the one this preview runs on — the branch that says the model is missing is
 * the *only* one reachable, which is exactly how the model running and saying
 * nothing went unnoticed until Sushi ran it on a machine that had one.
 *
 * The page the stub answers with is a small list-shaped one (ECE 411's shape,
 * which has no table on it), because that is the shape the deterministic search
 * returns nothing for and therefore the only one that reaches the model at all.
 */
const PREVIEW_SITE_URL = "https://courses.grainger.illinois.edu/ece411/fa2026/assignments.html";
const PREVIEW_SITE_HTML = [
  "<html><head><title>Assignments — ECE411 FA26</title></head><body>",
  '<section id="mp-information"><h2>MP Information</h2>',
  '<section id="mp-setup"><h3>mp_setup</h3>',
  '<ul class="simple"><li><p>Release: 8/25</p></li><li><p>Due: 9/7</p></li></ul></section>',
  '<section id="mp-verif"><h3>mp_verif</h3>',
  '<ul class="simple"><li><p>Release: 8/25</p></li><li><p>Due: 9/14</p></li></ul></section>',
  "</section></body></html>",
].join("");

const previewModel = query.get("model");

/*
 * `absent` has to *replace* the API, not decline to add one.
 *
 * The browser this harness runs in turned out to have `LanguageModel` already,
 * answering "downloadable" — so the branch that says the model is missing was
 * unreachable here, which is the same hole one level down from the one this
 * whole change is about. Deleting it does not work either: this script runs
 * before Chrome installs the global, so the delete is a no-op and the real one
 * appears afterwards.
 *
 * So it is replaced by one that throws, which `proposeWithModel` treats as
 * absent on purpose — "an API that is present and throws is an API that is not
 * there" — and which reaches the same sentence by the same branch.
 */
function installPreviewModel(stub: unknown): void {
  /*
   * Defined as a property that refuses to be replaced.
   *
   * Chrome installs the real `LanguageModel` on the window *after* the page's
   * own scripts run, by assignment, and it overwrote a stub assigned here —
   * even one re-assigned from a timeout. The harness then measured the machine
   * it happened to run on rather than the branch it was asked for, which is how
   * a laptop with the model and one without would both "verify" the same
   * screen. A getter with a setter that ignores writes survives it, and nothing
   * in the preview wants the real API.
   */
  Object.defineProperty(globalThis, "LanguageModel", {
    configurable: true,
    get: () => stub,
    set: () => undefined,
  });
}

if (previewModel === "absent") {
  installPreviewModel({
    availability: async () => {
      throw new Error("preview: no model on this computer");
    },
  });
}

if (previewModel === "ok" || previewModel === "fail") {
  const answer = JSON.stringify(
    previewModel === "ok"
      ? {
          shape: "list",
          rows: "#mp-information ul.simple > li",
          title: "p",
          due: "p",
          titleFrom: "section >> h3",
          dueLabel: "Due",
          dateFormat: "M/d",
        }
      : // A selector that matches nothing: the shape a model that invented an id
        // produces, and the one the status line has to quote a reason for.
        { shape: "list", rows: "#schedule > li", title: "p", due: "p", dueLabel: "Due", dateFormat: "M/d" },
  );
  installPreviewModel({
    availability: async () => "available",
    create: async () => ({
      contextWindow: 9216,
      prompt: async () => answer,
      destroy: () => undefined,
    }),
  });
}

/**
 * The worker's half of the add-site flow.
 *
 * Wrapped around the stub above rather than added to its switch, because the
 * switch is in the middle of a file two workers are editing. Everything it does
 * not answer falls through to what answered before.
 */
const previousSendMessage = (globalThis as unknown as {
  chrome: { runtime: { sendMessage: (req: { type: string }) => Promise<unknown> } };
}).chrome.runtime.sendMessage;

(globalThis as unknown as {
  chrome: { runtime: { sendMessage: (req: { type: string }) => Promise<unknown> } };
}).chrome.runtime.sendMessage = async (req: { type: string }) => {
  if (req.type === "detect-adapter") {
    // No candidates, with the page and the reason — which is the branch that
    // reaches the model. `?model=absent` (or no switch at all) stops here, the
    // way a student's laptop does.
    return {
      type: "detected",
      candidates: [],
      url: PREVIEW_SITE_URL,
      html: PREVIEW_SITE_HTML,
      courseCodeGuess: "ECE411",
      reason:
        "No table on this page. Either the schedule is built by JavaScript after the page " +
        "loads, which this cannot read, or it is a list rather than a table.",
    };
  }
  return previousSendMessage(req);
};

/** Acceptance instrumentation is preview-only. Unknown writes must not claim
 * success: record a harness gap, which is distinct from a product defect.
 */
if (query.has("acceptance")) {
  const host = globalThis as unknown as {
    chrome: {
      runtime: { sendMessage: (req: { type: string }) => Promise<Record<string, unknown>>; openOptionsPage: () => unknown };
      tabs: { create: (details: unknown) => unknown };
      permissions: { contains: () => Promise<boolean>; request: () => Promise<boolean> };
    };
    __UI_ACCEPTANCE__: { dataset: string; events: Record<string, unknown>[] };
  };
  const events: Record<string, unknown>[] = [];
  host.__UI_ACCEPTANCE__ = { dataset: dataset ?? "stress", events };
  const known = new Set([
    "get-state", "get-options-state", "get-setup", "get-adapters", "ping", "sync",
    "add-manual-item", "edit-manual-item", "delete-manual-item", "complete-setup",
    "remove-local-adapter", "add-local-adapter", "set-adapter-enabled", "detect-adapter",
    "get-diagnostics", "export", "open-full-view",
  ]);
  const original = host.chrome.runtime.sendMessage;
  host.chrome.runtime.sendMessage = async (req) => {
    const supported = known.has(req.type);
    events.push({ kind: supported ? "simulated-message" : "unsupported", request: req });
    if (!supported) return { type: "error", message: `Preview does not simulate ${req.type}. This journey needs a stateful stub or an isolated Chrome check.` };
    const response = await original(req);
    if (req.type === "get-state" || req.type === "get-options-state") {
      if (dataset === "reference" || dataset === "empty") {
        response.suggestions = [];
        response.courseNames = {};
        if (req.type === "get-options-state") {
          response.courses = [...new Set(items.map((i) => i.courseLabel))].map((code) => ({ key: code, label: code, itemCount: items.filter((i) => i.courseLabel === code).length, sources: [...new Set(items.filter((i) => i.courseLabel === code).flatMap((i) => i.members.map((m) => m.source)))], disabled: false }));
          response.hiddenItems = [];
          response.doneItems = [];
        }
      }
      const observer = query.get("observer") ?? "login";
      if (!["off", "pending", "read", "login", "error"].includes(observer)) throw new Error(`Unknown preview observer state: ${observer}`);
      response.observers = {
        campuswire: { enabled: observer !== "off", ...(observer === "read" ? { lastObservedAt: new Date(now).toISOString(), postsSeen: 3 } : {}) },
        piazza: { enabled: observer !== "off", state: observer === "read" ? "ok" : observer === "login" ? "needs_login" : observer === "error" ? "error" : "pending",
          ...(observer === "read" || observer === "login" || observer === "error" ? { lastAttemptAt: new Date(now).toISOString() } : {}),
          ...(observer === "read" ? { lastObservedAt: new Date(now).toISOString(), postsSeen: 25, deadlinesFound: 1 } : {}),
          ...(observer === "error" ? { lastError: "Preview: Piazza could not be reached" } : {}) },
      };
    }
    return response;
  };
  host.chrome.permissions.contains = async () => query.get("permission") !== "denied";
  host.chrome.permissions.request = async () => {
    const granted = query.get("permission") !== "denied";
    events.push({ kind: "simulated-permission", granted });
    return granted;
  };
  host.chrome.tabs.create = (details) => { events.push({ kind: "external-intent", details }); return Promise.resolve({}); };
  host.chrome.runtime.openOptionsPage = () => { events.push({ kind: "options-intent" }); return Promise.resolve(); };
}
