/**
 * Canned state for the popup preview (`npm run preview`).
 *
 * One row per shape the renderer has to handle, because these are exactly the
 * ones a real account rarely shows all at once: a late window still open, a
 * reduced-credit ladder, an unbooked CBTF exam, a merged two-source row, an
 * 8 AM smartPhysics checkpoint, a course-site row whose time was invented, a
 * not-for-credit practice quiz, a deadline that moved, and a date the parser
 * could not read. If the layout survives this list it survives a real one.
 *
 * Not shipped: nothing imports it, and `dist/preview.*` is regenerated by the
 * script rather than by the build.
 */
const now = Date.now();
const at = (days: number, hour = 23, minute = 59) => {
  const d = new Date(now + days * 86_400_000);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};
const member = (source: string, extra?: Record<string, string>, status = "not_submitted") => ({
  source, sourceId: `${source}-${Math.random()}`, courseRaw: "x", title: "m",
  kind: "assignment", url: "https://www.gradescope.com/", status, extra,
  fetchedAt: new Date().toISOString(),
});
const item = (o: Record<string, unknown>) => ({
  id: `i${Math.random()}`, members: [member("gradescope")], courseLabel: "CS357",
  title: "Thing", kind: "assignment", url: "https://www.gradescope.com/courses/1",
  status: "not_submitted", hidden: false, done: false, notified: {}, ...o,
});

const items = [
  // Real titles and shapes from Sushi's account, 2026-09-11. Invented titles
  // were consistently shorter than the ones UIUC courses actually use, which
  // is exactly the difference a layout fails on.
  item({ courseLabel: "CS357", title: "Book a slot: CS 357: Quiz 2", kind: "booking",
         members: [member("prairietest", { windowStart: at(10, 0, 1), windowEnd: at(12, 23, 59) })] }),
  // §4.4's room and duration, which the parser has recorded all along.
  // A December final: further out than the 60-day horizon every other view
  // stops at, which is the case the Exams tab exists for.
  item({ courseLabel: "CS357", title: "CS 357 Final Exam", dueAt: at(95, 8, 0), kind: "exam",
         members: [member("canvas", { location: "Foellinger Auditorium", duration: "180min" })] }),
  item({ courseLabel: "ECE374", title: "ECE 374 Midterm 2", dueAt: at(24, 19, 0), kind: "exam",
         members: [member("prairietest", { location: "Grainger Library",
                                           locationDetail: "Room 57", duration: "110min" })] }),
  item({ courseLabel: "CS357", title: "CS 357: Quiz 1", dueAt: at(0, 21, 0), kind: "exam",
         members: [member("prairietest", { location: "Grainger Library",
                                           locationDetail: "Room 57", duration: "50min" })] }),
  // ECE 374 guided problem sets, listed but not yet open. Real titles and real
  // opening times from the assessments page, 2026-09-11. Eight of these led the
  // list under "Couldn't read" before the parser knew the shape.
  item({ courseLabel: "ECE374", title: "GPS4 Language Transformations, and CFGs",
         members: [member("prairielearn", { releasedAt: at(1, 9, 0) })] }),
  item({ courseLabel: "ECE374", title: "GPS5 Divide and Conquer, Recursion, and Recurrences",
         members: [member("prairielearn", { releasedAt: at(15, 9, 0) })] }),
  // Canvas calendar events, from the same real list. The recurring one is the
  // point: four instances of this block and two class Zoom links were sitting
  // in "Needs attention", where nothing could ever clear them.
  item({ courseLabel: "CS411", title: "Fall 2026 Office Hours", dueAt: at(0, 20, 0),
         kind: "event", members: [member("canvas")] }),
  item({ courseLabel: "CS411", title: "Class Zoom (only for students with excused absence)",
         dueAt: at(1, 14, 0), kind: "event", members: [member("canvas")] }),
  item({ courseLabel: "CS425", title: "MP1 Report (4cr only, EXCEPT for students in MC3)",
         dueAt: at(3, 23, 59), members: [member("gradescope")] }),
  item({ courseLabel: "CS357", title: "L5 Rounding and Cancellation", dueAt: at(4, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "L6 Taylor Series", dueAt: at(4, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "HW5 Rounding and Cancellation", dueAt: at(4, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "PHYS435", title: "Homework 3", dueAt: at(5, 17),
         members: [member("gradescope")] }),
  item({ courseLabel: "CS424", title: "Homework 1", dueAt: at(5, 23, 59),
         members: [member("canvas"), member("site")] }),
  item({ courseLabel: "CS357", title: "HW6 Taylor Series", dueAt: at(6, 23),
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS425", title: "HW1", dueAt: at(9, 23, 59),
         members: [member("gradescope")] }),
  // Listed by a source with no date on it anywhere. Three of them, so the
  // folded group has something to fold — it is the shape that made Attention
  // read "11" when one thing was actually late.
  item({ courseLabel: "CS357", title: "Research study survey (extra credit)",
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "Select your group (NOT FOR CREDIT)",
         members: [member("prairielearn")] }),
  item({ courseLabel: "CS411", title: "Course syllabus acknowledgement",
         members: [member("canvas")] }),
  // Today at 11:59 PM — the commonest deadline there is, and the one the
  // harness was missing. An item on the last minute of the grid is drawn one
  // pixel before the bottom edge, and its wrapped lines landed on top of the
  // status line underneath. The fixture day had nothing at 11:59 PM, so the
  // preview could not reproduce it and Sushi found it on real data instead.
  item({ courseLabel: "CS425", title: "MP1 Report (4cr only, EXCEPT Coursera)",
         dueAt: at(0, 23, 59), members: [member("gradescope")] }),
  // Today, so the untimed band has something in it: the band is the row shape
  // that is hardest to see in the extension and easiest to get wrong.
  item({ courseLabel: "CS424", title: "Homework 1", dueAt: at(0, 23, 59), timeAssumed: true,
         members: [member("site", { timeAssumed: "true" })] }),
  item({ courseLabel: "CS424", title: "HW2 Due", dueAt: at(12, 23, 59), timeAssumed: true,
         members: [member("site", { timeAssumed: "true" })] }),
  // Shapes his account does not currently have, kept so the layout is still
  // exercised against them: a still-open late window, a reduced-credit ladder,
  // an 8 AM smartPhysics checkpoint, a practice quiz, a moved deadline, and a
  // date the parser could not read.
  item({ courseLabel: "PHYS435", title: "Homework 2", dueAt: at(-1, 17, 0),
         lateDueAt: at(6, 17, 0), members: [member("gradescope")] }),
  item({ courseLabel: "CS357", title: "L4a Floating Point", dueAt: at(-2, 11),
         lateDueAt: at(12, 23), members: [member("prairielearn", { creditRemaining: "80" })] }),
  item({ courseLabel: "PHYS214", title: "Harmonic waves — Checkpoint", dueAt: at(0, 8, 0),
         kind: "quiz", members: [member("smartphysics", { creditRemaining: "100" })] }),
  item({ courseLabel: "CS357", title: "PQ1 Practice Quiz 1 (NOT FOR CREDIT)", dueAt: at(1, 23),
         forCredit: false, members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "HW4a Errors and Big-O", dueAt: at(2, 23),
         movedFrom: at(1, 23), members: [member("prairielearn")] }),
  item({ courseLabel: "CS425", title: "Reading response 4",
         members: [member("gradescope", { unparsedDueDate: "2026-09-31 17:00:00 -0500" })] }),
];

let setupDone = false;

const sources = {
  canvas: { source: "canvas", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  gradescope: { source: "gradescope", enabled: true, state: "needs_login", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date(now - 40 * 3600_000).toISOString(), lastError: "401 at https://www.gradescope.com/login", consecutiveFailures: 2 },
  prairielearn: { source: "prairielearn", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  prairietest: { source: "prairietest", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  smartphysics: { source: "smartphysics", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  site: { source: "site", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
};

(globalThis as unknown as { chrome: unknown }).chrome = {
  runtime: {
    sendMessage: async (req: { type: string }) => {
      // `?setup=1` shows the first-run screen, which is otherwise reachable
      // only by installing the extension into a clean Chrome profile — the
      // single hardest state in this project to look at.
      if (req.type === "complete-setup") {
        setupDone = true;
        return { type: "ok" };
      }
      if (req.type === "get-setup") {
        if (setupDone || !new URLSearchParams(location.search).has("setup")) {
          return { type: "setup" };
        }
        return {
          type: "setup",
          rows: [
            { source: "canvas", label: "Canvas", hint: "Every UIUC course",
              enabled: true, status: { ...sources.canvas, state: "ok" } },
            { source: "gradescope", label: "Gradescope", hint: "Most CS, ECE and Math courses",
              enabled: true, status: { source: "gradescope", enabled: true, state: "needs_login", consecutiveFailures: 1 } },
            { source: "prairielearn", label: "PrairieLearn", hint: "CS and ECE homework and quizzes",
              enabled: true, status: { source: "prairielearn", enabled: true, state: "pending", consecutiveFailures: 0 } },
            { source: "prairietest", label: "PrairieTest", hint: "Exams booked at the CBTF",
              enabled: false, status: { source: "prairietest", enabled: false, state: "disabled", consecutiveFailures: 0 } },
            { source: "smartphysics", label: "smartPhysics", hint: "PHYS 211, 212, 213 and 214 only",
              enabled: false, status: { source: "smartphysics", enabled: false, state: "disabled", consecutiveFailures: 0 } },
          ],
        };
      }
      if (req.type === "get-state") {
        return { type: "state", items, sources, notificationsBlocked: false,
                 settings: { leadTimes: ["24h", "2h"], quietHours: { start: 23, end: 8 },
                             hideSubmitted: true, remindNotForCredit: false, pollMinutes: 30 },
                 lastSyncAt: new Date().toISOString() };
      }
      return { type: "ok" };
    },
    getURL: (p: string) => p,
    openOptionsPage: () => undefined,
  },
  tabs: { create: () => undefined },
  // Present because the real page has it, not because the preview needs it.
  // The live-refresh listener threw here and the harness said nothing — the
  // same shape as every other bug this preview has missed: a state it could
  // not reach. `fireStorageChange()` on the console drives a redraw.
  storage: {
    local: { get: async () => ({}), set: async () => undefined },
    onChanged: {
      addListener: (fn: (changes: unknown, area: string) => void) => {
        (globalThis as unknown as { fireStorageChange: () => void }).fireStorageChange = () =>
          fn({ illiniDue: { newValue: {} } }, "local");
      },
    },
  },
};
