/**
 * Canned state for the popup preview (`npm run preview`).
 *
 * One row per shape the renderer has to handle, because these are exactly the
 * ones a real account rarely shows all at once: a late window still open, a
 * reduced-credit ladder, an unbooked CBTF exam, a merged two-source row, an
 * 8 AM smartPhysics checkpoint, a course-site row whose time was invented, a
 * not-for-credit practice quiz, a deadline that moved, and a date the parser
 * could not read. If the layout survives this list it survives a real one.
 *
 * Not shipped: nothing imports it, and `dist/preview.*` is regenerated by the
 * script rather than by the build.
 */
const now = Date.now();
const at = (days: number, hour = 23, minute = 59) => {
  const d = new Date(now + days * 86_400_000);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};
const member = (source: string, extra?: Record<string, string>, status = "not_submitted") => ({
  source, sourceId: `${source}-${Math.random()}`, courseRaw: "x", title: "m",
  kind: "assignment", url: "https://www.gradescope.com/", status, extra,
  fetchedAt: new Date().toISOString(),
});
const item = (o: Record<string, unknown>) => ({
  id: `i${Math.random()}`, members: [member("gradescope")], courseLabel: "CS357",
  title: "Thing", kind: "assignment", url: "https://www.gradescope.com/courses/1",
  status: "not_submitted", hidden: false, done: false, notified: {}, ...o,
});

const items = [
  item({ courseLabel: "PHYS435", title: "Homework 2", dueAt: at(-1, 17, 0),
         lateDueAt: at(6, 17, 0), members: [member("gradescope")] }),
  item({ courseLabel: "CS357", title: "L4a Floating Point", dueAt: at(-2, 11),
         lateDueAt: at(12, 23), members: [member("prairielearn", { creditRemaining: "80" })] }),
  item({ courseLabel: "CS357", title: "Book a slot: Quiz 2", kind: "booking",
         members: [member("prairietest", { windowStart: at(11, 0, 1), windowEnd: at(13, 23, 59) })] }),
  item({ courseLabel: "CS425", title: "MP1 Distributed Logging", dueAt: at(0, 23, 59),
         members: [member("gradescope"), member("canvas")] }),
  item({ courseLabel: "PHYS214", title: "Harmonic waves — Checkpoint", dueAt: at(0, 8, 0),
         kind: "quiz", members: [member("smartphysics", { creditRemaining: "100" })] }),
  item({ courseLabel: "CS424", title: "HW2", dueAt: at(1, 23, 59), timeAssumed: true,
         members: [member("site", { timeAssumed: "true" })] }),
  item({ courseLabel: "CS357", title: "PQ1 Practice Quiz 1 (NOT FOR CREDIT)", dueAt: at(1, 23),
         forCredit: false, members: [member("prairielearn")] }),
  item({ courseLabel: "CS357", title: "HW4a Errors and Big-O", dueAt: at(3, 23),
         movedFrom: at(1, 23), members: [member("prairielearn")] }),
  item({ courseLabel: "ECE310", title: "Homework 3", dueAt: at(6, 23, 59),
         members: [member("site")] }),
  item({ courseLabel: "CS425", title: "Reading response 4",
         members: [member("gradescope", { unparsedDueDate: "2026-09-31 17:00:00 -0500" })] }),
  item({ courseLabel: "CS357", title: "GA 5 Linear Systems", dueAt: at(14, 23),
         members: [member("prairielearn")] }),
];

const sources = {
  canvas: { source: "canvas", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  gradescope: { source: "gradescope", enabled: true, state: "needs_login", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date(now - 40 * 3600_000).toISOString(), lastError: "401 at https://www.gradescope.com/login", consecutiveFailures: 2 },
  prairielearn: { source: "prairielearn", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  prairietest: { source: "prairietest", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  smartphysics: { source: "smartphysics", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
  site: { source: "site", enabled: true, state: "ok", lastAttemptAt: new Date().toISOString(), lastSuccessAt: new Date().toISOString(), consecutiveFailures: 0 },
};

(globalThis as unknown as { chrome: unknown }).chrome = {
  runtime: {
    sendMessage: async (req: { type: string }) => {
      if (req.type === "get-state") {
        return { type: "state", items, sources, notificationsBlocked: false,
                 settings: { leadTimes: ["24h", "2h"], quietHours: { start: 23, end: 8 },
                             hideSubmitted: true, remindNotForCredit: false, pollMinutes: 30 },
                 lastSyncAt: new Date().toISOString() };
      }
      return { type: "ok" };
    },
    getURL: (p: string) => p,
    openOptionsPage: () => undefined,
  },
  tabs: { create: () => undefined },
};
